mecanum_drive_controller:
  ros__parameters:
    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_left_wheel_command_joint_name: "rear_left_wheel_joint"
    rear_right_wheel_command_joint_name: "rear_right_wheel_joint"
    kinematics:
      wheels_radius: 0.03
      sum_of_robot_center_projection_on_X_Y_axis: 0.2925
      base_frame_offset: {x: 0.0, y: 0.0, theta: 0.0}
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    enable_odom_tf: true
