joy_to_twist:
  ros__parameters:
    axis_linear.x: 1
    axis_linear.y: 0
    axis_angular.yaw: 3

    scale_linear.x: 1.0
    scale_linear.y: 1.0
    scale_angular.yaw: 1.0

    enable_button: 5
    enable_turbo_button: 4
    turbo_scale: 2.0

    deadzone: 0.05
